import {
  BtnAddClient,
  BtnAddInvitation,
  BtnAddProduct,
  BtnAddProductCirculation,
  BtnAddProductType,
  BtnAddSet,
  BtnAddSetType,
  BtnTest,
} from '@components/TitleButtons'
import {
  InvitationsContent,
  ProductCirculationsContent,
  ProductsContent,
  ProductTypesContent,
  SetsContent,
  SettingsContent,
  SetTypesContent,
  TestContent,
  UserContent,
  UsersContent,
} from './content'
import ClientsContent from './content/ClientsContent'
import OverviewContent from './content/OverviewContent'

export const pages = [
  {
    id: 0,
    group: 0,
    name: 'Обзор',
    pageContent: OverviewContent,
    pageButtons: [],
    backToPageId: null,
    accessRoles: ['admin'],
    variable: null,
  }, // 3
  {
    id: 1,
    group: 1,
    name: 'Товары',
    pageContent: ProductsContent,
    pageButtons: [BtnAddProduct],
    backToPageId: null,
    accessRoles: ['admin', 'operator', 'aerodesigner'],
    variable: 'products',
  }, // 0
  {
    id: 2,
    group: 1,
    name: 'Типы товаров',
    pageContent: ProductTypesContent,
    pageButtons: [BtnAddProductType],
    backToPageId: null,
    accessRoles: ['admin'],
    variable: 'productTypes',
  }, // 1
  {
    id: 3,
    group: 1,
    name: 'Наборы',
    pageContent: SetsContent,
    pageButtons: [BtnAddSet],
    backToPageId: null,
    accessRoles: ['admin', 'operator', 'aerodesigner'],
    variable: 'sets',
  }, // 2
  {
    id: 4,
    group: 1,
    name: 'Типы наборов',
    pageContent: SetTypesContent,
    pageButtons: [BtnAddSetType],
    backToPageId: null,
    accessRoles: ['admin'],
    variable: 'setTypes',
  }, // 1
  {
    id: 5,
    group: null,
    name: 'Параметры учетной записи',
    pageContent: UserContent,
    pageButtons: [],
    backToPageId: null,
    variable: null,
  }, // 3
  {
    id: 6,
    group: 4,
    name: 'Сотрудники',
    pageContent: UsersContent,
    pageButtons: [],
    backToPageId: null,
    accessRoles: ['admin'],
    variable: 'users',
  }, // 3
  {
    id: 7,
    group: 4,
    name: 'Приглашения',
    pageContent: InvitationsContent,
    pageButtons: [BtnAddInvitation],
    backToPageId: null,
    accessRoles: ['admin'],
    variable: 'invitations',
  },
  {
    id: 8,
    group: 5,
    name: 'Настройки',
    pageContent: SettingsContent,
    pageButtons: [],
    backToPageId: 0,
    accessRoles: ['admin'],
    variable: null,
  },
  {
    id: 9,
    group: 2,
    name: 'Движение товаров',
    pageContent: ProductCirculationsContent,
    pageButtons: [BtnAddProductCirculation],
    backToPageId: 0,
    accessRoles: ['admin'],
    variable: 'productCirculations',
  },
  {
    id: 10,
    group: 3,
    name: 'Клиенты',
    pageContent: ClientsContent,
    pageButtons: [BtnAddClient],
    backToPageId: 0,
    accessRoles: ['admin'],
    variable: 'clients',
  },
  {
    id: 11,
    group: 3,
    name: 'Заказы',
    pageContent: null,
    pageButtons: [],
    backToPageId: 0,
    accessRoles: ['admin'],
    variable: 'orders',
  },
  {
    id: 12,
    group: 3,
    name: 'Транзакции',
    pageContent: null,
    pageButtons: [],
    backToPageId: 0,
    accessRoles: ['admin'],
    variable: 'payments',
  },
  {
    id: 99,
    group: 10,
    name: 'Тестовая страница',
    pageContent: TestContent,
    pageButtons: [BtnTest],
    backToPageId: 0,
    accessRoles: [],
    variable: null,
  },
]

export const pagesGroups = [
  { id: 0, name: '' },
  { id: 1, name: 'Продукция' },
  { id: 2, name: 'Склад' },
  { id: 3, name: 'Воронка' },
  { id: 4, name: 'Пользователи' },
  { id: 5, name: 'Настройки' },
  { id: 10, name: 'Разработка' },
]
