export const SET_PRODUCTS = 'SET_PRODUCTS'
export const ADD_COUNT_TO_PRODUCTS = 'ADD_COUNT_TO_PRODUCTS'
export const SET_SETS = 'SET_SETS'
export const ADD_COUNT_TO_SETS = 'ADD_COUNT_TO_SETS'
export const SET_PRODUCT_TYPES = 'SET_PRODUCT_TYPES'
export const SET_SET_TYPES = 'SET_SET_TYPES'
export const SET_INVITATIONS = 'SET_INVITATIONS'
export const SET_USERS = 'SET_USERS'
export const SET_PRODUCT_CIRCULATIONS = 'SET_PRODUCT_CIRCULATIONS'
export const SET_CLIENTS = 'SET_CLIENTS'
export const SET_ORDERS = 'SET_ORDERS'
export const SET_PAYMENTS = 'SET_PAYMENTS'
export const SET_DEVTODO = 'SET_DEVTODO'
export const SET_DISTRICTS = 'SET_DISTRICT'

export const SET_MODAL = 'SET_MODAL'
export const ADD_MODAL = 'ADD_MODAL'
export const REMOVE_MODAL = 'REMOVE_MODAL'
export const REMOVE_ALL_MODALS = 'REMOVE_ALL_MODALS'

export const SET_FILTER = 'SET_FILTER'

export const SET_SORTING = 'SET_SORTING'

export const SET_PAGE = 'SET_PAGE'

export const SET_LOADED = 'SET_LOADED'

export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS'
export const SET_NOTIFICATION_VIEWED = 'SET_NOTIFICATION_VIEWED'
