export const SET_PRODUCTS = 'SET_PRODUCTS'
export const ADD_COUNT_TO_PRODUCTS = 'ADD_COUNT_TO_PRODUCTS'
export const SET_SETS = 'SET_SETS'
export const ADD_COUNT_TO_SETS = 'ADD_COUNT_TO_SETS'
export const SET_PRODUCT_TYPES = 'SET_PRODUCT_TYPES'
export const SET_SET_TYPES = 'SET_SET_TYPES'
export const SET_INVITATIONS = 'SET_INVITATIONS'
export const SET_USERS = 'SET_USERS'
export const SET_PRODUCT_CIRCULATIONS = 'SET_PRODUCT_CIRCULATIONS'

export const SET_MODAL = 'SET_MODAL'
export const ADD_MODAL = 'ADD_MODAL'
export const REMOVE_MODAL = 'REMOVE_MODAL'
export const REMOVE_ALL_MODALS = 'REMOVE_ALL_MODALS'

//Filters
// export const SET_PRODUCTS_FILTER = 'SET_PRODUCTS_FILTER'
// export const SET_SETS_FILTER = 'SET_SETS_FILTER'
// export const SET_PRODUCT_CIRCULSTIONS_FILTER = 'SET_PRODUCT_CIRCULSTIONS_FILTER'
// export const SET_PRODUCT_TYPES_FILTER = 'SET_PRODUCT_TYPES_FILTER'
// export const SET_SET_TYPES_FILTER = 'SET_SET_TYPES_FILTER'
// export const SET_USERS_FILTER = 'SET_USERS_FILTER'
// export const SET_INVITATIONS_FILTER = 'SET_USERS_FILTER'
export const SET_FILTER = 'SET_FILTER'

// Sorting
export const SET_SORTING = 'SET_SORTING'

export const SET_PAGE = 'SET_PAGE'
